// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArLWzoAOBAsKEVM4hGlr6o59VfEb7qcr0',
    appId: '1:206371356670:web:4e843f5b201bef0d150aaf',
    messagingSenderId: '206371356670',
    projectId: 'my-notes-ef8ad',
    authDomain: 'my-notes-ef8ad.firebaseapp.com',
    storageBucket: 'my-notes-ef8ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRKoevNAVtdpZfMOA1rdYQJLaTDgFBgRA',
    appId: '1:206371356670:android:ed8437c2e966f9ec150aaf',
    messagingSenderId: '206371356670',
    projectId: 'my-notes-ef8ad',
    storageBucket: 'my-notes-ef8ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9BzkOrnPmLZNrzc21dKXBrNZI9FuxsKs',
    appId: '1:206371356670:ios:2774c1417330521d150aaf',
    messagingSenderId: '206371356670',
    projectId: 'my-notes-ef8ad',
    storageBucket: 'my-notes-ef8ad.firebasestorage.app',
    androidClientId: '206371356670-su108ui1klj4og94j5qf9buod9nvpcbl.apps.googleusercontent.com',
    iosClientId: '206371356670-9edc9c5pukp85qklju57haeh8u52ehka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9BzkOrnPmLZNrzc21dKXBrNZI9FuxsKs',
    appId: '1:206371356670:ios:2774c1417330521d150aaf',
    messagingSenderId: '206371356670',
    projectId: 'my-notes-ef8ad',
    storageBucket: 'my-notes-ef8ad.firebasestorage.app',
    androidClientId: '206371356670-su108ui1klj4og94j5qf9buod9nvpcbl.apps.googleusercontent.com',
    iosClientId: '206371356670-9edc9c5pukp85qklju57haeh8u52ehka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArLWzoAOBAsKEVM4hGlr6o59VfEb7qcr0',
    appId: '1:206371356670:web:d3022ef5863be50b150aaf',
    messagingSenderId: '206371356670',
    projectId: 'my-notes-ef8ad',
    authDomain: 'my-notes-ef8ad.firebaseapp.com',
    storageBucket: 'my-notes-ef8ad.firebasestorage.app',
  );

}